apiVersion: v1
kind: Service
metadata:
   name: airflow-service
   labels:
      name: airflow-service
      app: myapp
spec:
   type: ClusterIP
   ports:
      - port: 8080
        targetPort: 8080
   selector:
      name: puckel-pod
      app: myapp
